// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.model;

import java.io.Serializable;

import edu.iris.Fissures.FlinnEngdahlRegion;
import edu.iris.Fissures.FlinnEngdahlType;

//
// IDL:iris.edu/Fissures/FlinnEngdahlRegion:1.0
//
/***/

public class FlinnEngdahlRegionImpl extends FlinnEngdahlRegion {

    public FlinnEngdahlRegionImpl(FlinnEngdahlType type,
                                  int number) {
        this.type = type;
        this.number = number;
    }

    protected  FlinnEngdahlRegionImpl() {}

    public static Serializable createEmpty() {
        return new  FlinnEngdahlRegionImpl();
    }

    /** for use by hibernate */
    public int getTypeAsInt() {
        return type.value();
    }

    /** for use by hibernate */
    protected void setTypeAsInt(int type) {
        this.type = FlinnEngdahlType.from_int(type);
    }
    
    public String toString() {
        if (type.equals(FlinnEngdahlType.GEOGRAPHIC_REGION)) {
            return "Geo FERegion "+number;
        } else {
            return "Seis FERegion "+number;
        }
    }

    public boolean equals(Object o){
        if(o == this){ return true; }
        else if(o instanceof FlinnEngdahlRegion){
            FlinnEngdahlRegion oRegion = (FlinnEngdahlRegion)o;
            if(oRegion.number == number &&
               type == oRegion.type){
                return true;
            }
        }
        return false;
    }

    public int hashCode(){
        if(type == FlinnEngdahlType.GEOGRAPHIC_REGION){ return number; }
        else{ return number * -1;}
    }
}
