// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.network;


//
// IDL:iris.edu/Fissures/IfNetwork/Calibration:1.0
//
/***/

public class CalibrationImpl extends edu.iris.Fissures.IfNetwork.Calibration
{

    private CalibrationImpl() {
    }

    public static CalibrationImpl createEmpty() {
	return new CalibrationImpl();
    }

    public  CalibrationImpl(float frequency,
                            float sensitivity) {
        this.frequency = frequency;
        this.sensitivity = sensitivity;
    }

}
