// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************
// Version: 4.0.3
package edu.iris.Fissures.network;

import edu.iris.Fissures.Time;
import edu.iris.Fissures.TimeRange;
import edu.iris.Fissures.IfNetwork.NetworkAttr;
import edu.iris.Fissures.IfNetwork.NetworkId;

//
// IDL:iris.edu/Fissures/IfNetwork/NetworkAttr:1.0
//
/***/
public class NetworkAttrImpl extends edu.iris.Fissures.IfNetwork.NetworkAttr {

    protected NetworkAttrImpl() {}

    public static NetworkAttrImpl createEmpty() {
        return new NetworkAttrImpl();
    }

    public NetworkAttrImpl(NetworkId id,
                           String name,
                           String description,
                           String owner,
                           TimeRange effective_time) {
        this.id = id;
        this.setName(name);
        this.setDescription(description);
        this.setOwner(owner);
        this.setEffectiveTime(effective_time);
    }

    /**
     * creates a net NetworkAttr with effective begin extracted from the
     * NetworkId and effective end unknown, ie still operational.
     */
    public NetworkAttrImpl(NetworkId id,
                           String name,
                           String description,
                           String owner) {
        this(id,
             name,
             description,
             owner,
             new TimeRange(id.begin_time,
                           edu.iris.Fissures.model.TimeUtils.timeUnknown));
    }

    //
    // IDL:iris.edu/Fissures/IfNetwork/NetworkAttr/get_id:1.0
    //
    public NetworkId get_id() {
        return id;
    }

    //
    // IDL:iris.edu/Fissures/IfNetwork/NetworkAttr/get_code:1.0
    //
    public String get_code() {
        return id.network_code;
    }
    
    /** Updates the network begintime in the networkId and effective time. Usually this is
     * because of a change in a remote database causing a local update to be needed.
     */
    public void updateBeginTime(Time t) {
        getId().begin_time = t;
        setBeginTime(t);
    }
    
    protected int dbid;
    protected String sourceServerName;
    protected String sourceServerDNS;
    
    
    public String getSourceServerName() {
        return sourceServerName;
    }

    public void setSourceServerName(String sourceServerName) {
        this.sourceServerName = sourceServerName;
    }
    
    public String getSourceServerDNS() {
        return sourceServerDNS;
    }
    
    public void setSourceServerDNS(String sourceServerDNS) {
        this.sourceServerDNS = sourceServerDNS;
    }

    protected void setDbid(int dbid) {
        this.dbid = dbid;
    }
    public int getDbid() {
        return dbid;
    }
    public void associateInDB(NetworkAttrImpl attr) {
        setDbid(attr.getDbid());
    }
    
    public boolean equals(Object o) {
    	if (o instanceof NetworkAttr) {
    		NetworkAttr n = (NetworkAttr)o;
    		return NetworkIdUtil.areEqual(get_id(), n.get_id());
    	}
    	return false;
    }
    
    public int hashCode() {
    	return NetworkIdUtil.hashCode(get_id());
    }
}
