// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.network;

import edu.iris.Fissures.Orientation;
import edu.iris.Fissures.Quantity;
import edu.iris.Fissures.IfNetwork.OrientationRange;

//
// IDL:iris.edu/Fissures/IfNetwork/OrientationRange:1.0
//
/***/

public class OrientationRangeImpl extends OrientationRange
{

	protected OrientationRangeImpl() {
    }

    public static OrientationRange createEmpty() {
	return new OrientationRangeImpl();
    }

    public  OrientationRangeImpl(Orientation center,
                                 Quantity angular_distance) {
        this.center = center;
        this.angular_distance =  angular_distance;
    }

}
