// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.network;

import edu.iris.Fissures.Quantity;
import edu.iris.Fissures.TimeRange;
import edu.iris.Fissures.IfNetwork.TimeCorrection;

//
// IDL:iris.edu/Fissures/IfNetwork/TimeCorrection:1.0
//
/***/

public class TimeCorrectionImpl extends TimeCorrection
{

	protected TimeCorrectionImpl() {
    }

    public static TimeCorrectionImpl createEmpty() {
	return new TimeCorrectionImpl();
    }

    public TimeCorrectionImpl(TimeRange effective_time,
			      Quantity begin_offset,
			      Quantity end_offset) {
	this.effective_time = effective_time;
	this.begin_offset = begin_offset;
	this.end_offset = end_offset;
    }

}
