// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.model;

import java.io.Serializable;
import edu.iris.Fissures.PointDistanceArea;
import edu.iris.Fissures.Quantity;

//
// IDL:iris.edu/Fissures/PointDistanceArea:1.0
//
/***/

public class PointDistanceAreaImpl extends PointDistanceArea
{

    public PointDistanceAreaImpl(float latitude,
                 float longitude,
                 Quantity min_distance,
                 Quantity max_distance) {
    this.latitude = latitude;
    this.longitude = longitude;
    this.min_distance = min_distance;
    this.max_distance = max_distance;
    }

    protected PointDistanceAreaImpl() {

    }

    public static Serializable createEmpty() {
        return new PointDistanceAreaImpl();
    }

    public String toString() {
        return "PointDistance ("+latitude+","+longitude+") from "+min_distance+" to "+max_distance;
    }
}
