// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.network;

import edu.iris.Fissures.TimeRange;
import edu.iris.Fissures.IfNetwork.Clock;
import edu.iris.Fissures.IfNetwork.DataAcqSys;
import edu.iris.Fissures.IfNetwork.Instrumentation;
import edu.iris.Fissures.IfNetwork.Response;
import edu.iris.Fissures.IfNetwork.Sensor;

//
// IDL:iris.edu/Fissures/IfNetwork/Instrumentation:1.0
//
/***/

public class InstrumentationImpl extends Instrumentation
{
	protected InstrumentationImpl() {
    }

    public static InstrumentationImpl createEmpty() {
	return new InstrumentationImpl();
    }

    public InstrumentationImpl(Response the_response,
                               TimeRange effective_time,
                               Clock the_clock,
                               Sensor the_sensor,
                               DataAcqSys das) {
        this.the_response = the_response;
        this.effective_time = effective_time;
        this.the_clock = the_clock;
        this.the_sensor =  the_sensor;
        this.das = das;
    }

}
