// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.network;

import edu.iris.Fissures.Sampling;
import edu.iris.Fissures.IfNetwork.SamplingRange;

//
// IDL:iris.edu/Fissures/IfNetwork/SamplingRange:1.0
//
/***/

public class SamplingRangeImpl extends SamplingRange
{

	protected SamplingRangeImpl() {
    }

    public static SamplingRange createEmpty() {
	return new SamplingRangeImpl();
    }

    public SamplingRangeImpl(Sampling min,
                             Sampling max) {
        this.min = min;
        this.max = max;
    }

}
