// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.network;

import edu.iris.Fissures.IfNetwork.SeismicHardware;

//
// IDL:iris.edu/Fissures/IfNetwork/SeismicHardware:1.0
//
/***/

public class SeismicHardwareImpl extends SeismicHardware
{

	protected SeismicHardwareImpl() {
    }

    public static SeismicHardware createEmpty() {
	return new SeismicHardwareImpl();
    }

}
