// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.event;

import edu.iris.Fissures.FlinnEngdahlRegion;
import edu.iris.Fissures.FlinnEngdahlType;
import edu.iris.Fissures.IfEvent.EventAttr;
import edu.iris.Fissures.IfParameterMgr.ParameterRef;
import edu.iris.Fissures.model.FlinnEngdahlRegionImpl;
import edu.iris.Fissures.model.ParameterRefUtil;

//
// IDL:iris.edu/Fissures/IfEvent/EventAttr:1.0
//
/***/

public class EventAttrImpl extends EventAttr {
    public EventAttrImpl(String name) {
        this(name,
             new FlinnEngdahlRegionImpl(FlinnEngdahlType.GEOGRAPHIC_REGION, 0));
    }

    public EventAttrImpl(String name, FlinnEngdahlRegion region) {
        this(name, region, new ParameterRef[0]);
    }

    public EventAttrImpl(String name,
                         FlinnEngdahlRegion region,
                         ParameterRef[] params) {
        this.name = name;
        this.region = region;
        this.parm_ids = params;
    }

    protected EventAttrImpl() {
        this.parm_ids = new ParameterRef[0];
    }

    /** Only for use for CORBA object serialization. */
    public static EventAttrImpl createEmpty() {
        return new EventAttrImpl();
    }

    public int hashCode(){
        int result = 87;
        result = result*34 + name.hashCode();
        result = result*34 + region.hashCode();
        for (int i = 0; i < parm_ids.length; i++) {
            result += result *34 + ParameterRefUtil.hash(parm_ids[i]);
        }
        return result;
    }

    public boolean equals(Object o) {
        if(o == this){ return true; }
        else if(o instanceof EventAttr){
            EventAttr oAttr = (EventAttr)o;
            if(oAttr.name.equals(name) &&
               region.equals(oAttr.region) &&
               ParameterRefUtil.areEqual(parm_ids, oAttr.parm_ids)){
                return true;
            }
        }
        return false;
    }

    public FlinnEngdahlRegion getRegion() { return region; }

    public String getName() { return name; }
}
