// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.iris.Fissures.event;

import edu.iris.Fissures.Quantity;
import edu.iris.Fissures.IfEvent.PredictedArrival;
import edu.iris.Fissures.IfParameterMgr.ParameterRef;

//
// IDL:iris.edu/Fissures/IfEvent/PredictedArrival:1.0
//
/***/

public class PredictedArrivalImpl extends PredictedArrival
{

    public PredictedArrivalImpl(String id,
				String name,
				Quantity travel_time,
				Quantity ray_parameter,
				Quantity dtdh,
				String model_id,
				ParameterRef[] params ) {
 	this.id = id;
 	this.name = name;
 	this.travel_time = travel_time;
 	this.ray_parameter = ray_parameter;
 	this.dtdh = dtdh;
 	this.model_id = model_id;
	this.parm_ids = params;
    }

    public PredictedArrivalImpl(String id,
				String name,
				Quantity travel_time,
				Quantity ray_parameter,
				Quantity dtdh,
				String model_id) {
	this(id, 
	     name, 
	     travel_time,
	     ray_parameter, 
	     dtdh, 
	     model_id, 
	     new ParameterRef[0]);
    }

    private PredictedArrivalImpl() {
    }

    /** Only for use for CORBA object serialization. */
    public static PredictedArrivalImpl createEmpty() {
	return new PredictedArrivalImpl();
    }

}
